<?php
/************************************************************\
 *
 * File				header.inc
 *
 * Language			PHP
 *
 * Author			David Mack
 * Creation			01 juin 2016
 * modification
 *
 * Project			orgapha
 *
 \************************************************************/
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head> 
		<link rel="stylesheet" type="text/css" href="/orgapha/css/style.css">
	</head>
